### ISSUE TITLE
Issue inside storyblok-js-client when sycing datasources. Not affecting the actual syncing

### ISSUE THREAD

**Issue by marckraw** [sb-mig/sb-mig#209]
**Describe the bug**
There is a Bug inside `storyblok-js-client` when updating dimension value for datasource. It doesnt affect the actual syncing it with storyblok. It's just bug related to not returned proper json, and parsing emptiness.
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Response.json (node:internal/deps/undici/undici:6160:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async J._responseHandler (file:///Users/marckraw/Projects/OpenSource/sb-mig/node_modules/storyblok-js-client/dist/index.mjs:276:5)
    at async J._methodHandler (file:///Users/marckraw/Projects/OpenSource/sb-mig/node_modules/storyblok-js-client/dist/index.mjs:300:17)
✓ Datasource Entry Dimension value for 'tylko jedno dimension' and dimension 'user' was successfuly updated.
```

Here is respective issue in `storyblok-js-client` repo: https://github.com/storyblok/storyblok-js-client/issues/400

**Comment by marckraw** [comment]
should be already resolved in `beta`
